main_name: OAuth2
redirect_url: 'http://object.com'

log:
    log_file: 'logs/main.log'
    file_mode: a
    log_level: DEBUG
    logger: main_logger
    datefmt: '%d %b. %Y %H:%M:%S'
    verbose: True

db_config:
    database: mysql
    username: username
    password: password
    db_host: localhost
    db_name: login

redis_config:
    password: ~
    host: localhost
    port: 6379

model:
    uid_len: 32
    username_len: 32
    password_len: 32
    email_len: 256

security:
    global_salt: 'test'
    salt_len: 32

token:
    issuer: issuer
    audience: audience
    expiration: 
        access_token: 86400 #Seconds 3600 * 24
        refresh_token: 2592000 #Seconds 3600 * 24 * 30
    not_before: 3600 #Seconds
    server_key_file: 'credentials/example_server.key'

other:
    state_expiration: 3600 #Seconds
