main_name: OAuth2
redirect_url: 'http://object.com'

log:
    log_file: 'logs/main.log'
    file_mode: a
    log_level: DEBUG
    logger: main_logger
    datefmt: '%d %b. %Y %H:%M:%S'
    verbose: True

db_config:
    database: mysql
    username: username
    password: password
    db_host: your_db_host
    db_name: your_db_name

model:
    uid_len: 32
    username_len: 32
    password_len: 32
    email_len: 256

security:
    global_salt: 
    salt_len: 32

token:
    issuer:
    audiance:
    expiration: 72000 #Seconds 3600 * 20
